### ISSUE TITLE
如果可以，能做一个wordpress的迁移工具吗？

### ISSUE THREAD

**Issue by coderstory** [moxi624/mogu_blog_v2#12]
我本身是java开发，目前公司的项目也是spring cloud全家桶
看到这个project 有点手痒
还没看过数据库结构
不知道能不能迁移过来

**Comment by moxi624** [comment]
您好，感谢您的支持，不知道您说的迁移是怎么样的，如果您这边拥有Wordpress的博客表的话，也是可以把它做成和蘑菇博客一样表结构的Excel文件，然后进行导入的。

**Comment by coderstory** [comment]
文章里还有很多图片附件超链接什么的uri处理起来比较麻烦
wp应该是现在用户最多的博客系统
先写到todo里 有空写个处理工具

**Comment by moxi624** [comment]
好的，wordpress我没有接触过，后期可以看一下wordpress的表结构以及文件存储方式，然后在写个处理工具，目前来说是支持本地markdown文件的导入
