### ISSUE TITLE
The super admin has no web permission

### ISSUE THREAD

**Issue by zhangchunsheng** [moxi624/mogu_blog_v2#34]
![image](https://user-images.githubusercontent.com/831839/116338848-fc401a00-a80e-11eb-93f6-0b61bf2e50ea.png)

**Comment by zhangchunsheng** [comment]
The user need to config it by himself. I think the super admin should has all permission.

**Comment by moxi624** [comment]
Thank you for your advice, a future update will consider giving admin full permissions
