### ISSUE TITLE
It can't change ali_pay and weixin_pay by admin web page

### ISSUE THREAD

**Issue by zhangchunsheng** [moxi624/mogu_blog_v2#35]
![image](https://user-images.githubusercontent.com/831839/116342021-7e7f0d00-a814-11eb-9dfc-e605f1354477.png)

**Comment by zhangchunsheng** [comment]
The user need to change it in database. I think you can use Github Sponsor.

**Comment by moxi624** [comment]
![image](https://user-images.githubusercontent.com/18610136/116805108-9f1dce80-ab56-11eb-9914-ecbacabfe3ef.png)

You can modify the two-dimensional code picture through the management page

**Comment by zhangchunsheng** [comment]
Ok

**Comment by zhangchunsheng** [comment]
Ok
