### ISSUE TITLE
mogu_blog_v5.2 backend Management System has an vulnerability of uploading arbitrary files

### ISSUE THREAD

**Issue by shitmoutainC0de** [moxi624/mogu_blog_v2#62]
1.Black box pentesting

Using mogu2021:mogu2021 to log in the mogu_blog_v5.2 backend Management System.

![image](https://user-images.githubusercontent.com/96566383/157186244-d3e77ff9-2dac-420c-bce7-b6f1ea903a8e.png)

Find the Blog Management - Blog Management - Local-file Upload feature .
![image](https://user-images.githubusercontent.com/96566383/157186279-c44f2b18-29cc-4512-9ca7-87d2b58dcb7a.png)

Click this blue button to select a local image for uploading, and then click the green button to put the image to server side
![image](https://user-images.githubusercontent.com/96566383/157186295-6c7d33fc-7ddb-4505-bb82-70cf9547b4a5.png)

At this point, use the burp suite to capture the request packet.
![image](https://user-images.githubusercontent.com/96566383/157186319-807ba3a1-6115-4f3e-aa1b-1264bdcfeb38.png)

and then forward it to the Repeater module.

Try to send a request to upload a normal image and you can see that the image was uploaded successfully.

And the response packet returns the address information of the image.
![image](https://user-images.githubusercontent.com/96566383/157186355-5fefa9e9-b1e7-4633-abfe-0a6eca6ee687.png)

Splice the address in the response packet with the url to try to access the image we just uploaded .

The whole url :
[http://23.224.61.136:8600//blog/admin/png/2022/3/8/1646708813850.png](http://23.224.61.136:8600/blog/admin/png/2022/3/8/1646708813850.png)

You can see the successful access to the uploaded image.
![image](https://user-images.githubusercontent.com/96566383/157186387-b708e87f-7b0f-4717-8ad2-413b9b944232.png)

Back in the burp suite, try changing the contents of the file in the request package to xss payload，as well as trying to change the file name to an html suffix.
![image](https://user-images.githubusercontent.com/96566383/157186414-816ad458-60ad-41ba-a65b-994467e411e1.png)

You can see the successful upload and the file path in the response package.

Splice the file path to the url and open a new browser (without admin cookies/session/token) to try to access it.

The whole url :
http://23.224.61.136:8600///blog/admin/html/2022/3/8/1646709195222.html
![image](https://user-images.githubusercontent.com/96566383/157186425-660b69c5-d95b-448b-ac80-f9f35d5ff2f5.png)

You can see that the xss payload was successfully executed and that there is an arbitrary file to upload.

Try again to modify the request package and found that arbitrary file uploads were possible while the feature was intended to allow only image format files to be uploaded.

jsp:
![image](https://user-images.githubusercontent.com/96566383/157186441-85e809eb-c339-45c8-ad83-717ff9dddb71.png)

php:
![image](https://user-images.githubusercontent.com/96566383/157186469-65648b7c-42ee-4573-b728-4ad21d9b373a.png)

cpp:
![image](https://user-images.githubusercontent.com/96566383/157186488-b3ac1f7e-78f6-49ad-950f-eb30a0248e37.png)

2.White box pentest

Based on the url of the image upload request
 (/mogu-picture/file/pictures), we can tell that the class that handles the image upload function is located in the /mogu-picture subproject
![image](https://user-images.githubusercontent.com/96566383/157186502-b066b777-68a6-49d0-b32c-2bc3efa262a3.png)
![image](https://user-images.githubusercontent.com/96566383/157186516-88a8ba9e-df7e-4f2b-9dc7-84dc9d8eca38.png)

According to the request url (mogu-picture/file/pictures) continue to locate the FileRestApi.java class

mogu_blog/mogu_blog_v2/mogu_picture/src/main/java/com/moxi/mogublog/picture/restapi/FileRestApi.java
![image](https://user-images.githubusercontent.com/96566383/157186535-50930646-5e25-478a-9dc8-445d012e27dd.png)

With @RequestMapping("/file") you can see that all requests for the /file path will be processed by this class

And requests for the /file/pictures path are handled by the uploadPics() method of this class
![image](https://user-images.githubusercontent.com/96566383/157186551-4c4bdd9d-b3a9-4e09-91dd-65cf7aaf31f0.png)

This method first obtains the system configuration file, and this step does not perform any checks on the suffix name, format, or file content of the uploaded file

This method then calls the batchUploadFile() method of the FileServiceImpl class instance object  
![image](https://user-images.githubusercontent.com/96566383/157186616-275e42ab-9c5c-4ca3-a447-5fc37e5c6116.png)

Follow up in the batchUploadFile() method of the FileServiceImpl class to see its source code
![image](https://user-images.githubusercontent.com/96566383/157186636-29b425ee-24fe-44b8-a020-3b222deeecd6.png)

The first part of the code is to get some files and system base information, none of which is file-checked

Continuing to follow up to the code for file uploads,

You can see that there is no strict verification of the uploaded file extension, file content, or file format
![image](https://user-images.githubusercontent.com/96566383/157186650-1a3cba4d-e85e-4718-919d-8d16019c4107.png)

The next code execution reaches the try /catch {} block, which involves the uploadFile() method of the QiniuServiceImpl class
![image](https://user-images.githubusercontent.com/96566383/157186664-b1181eaa-8056-4526-873b-cf1cb3d3cbb1.png)

Going deeper into this method leads to the uploadSingleFile() method.
![image](https://user-images.githubusercontent.com/96566383/157186678-c5d3f4fb-966a-4923-bbc3-540a57ddd20c.png)

You can see that the file suffix, file format and file content are still not strictly verified.

Back in the batchUploadFile() method of the FileServiceImpl class,

After checking the code after , not only the code for uploading the QiNiu server did not have strict file verification, but also the code for uploading Minio server and the code for uploading to the local server was not strictly verified.

Finally, in the batchUploadFile() method of the FileServiceImpl class, the following code will be executed.
![image](https://user-images.githubusercontent.com/96566383/157186701-aa19fa04-a502-4139-936e-0790957da957.png)

Set the information of the uploaded file to some settings.

Then save and upload feedback to the client response file.

The entire code execution process does not strictly check the suffix name, file format, and file content of the uploaded files.

This allows attackers to use the file upload interface to upload arbitrary files and even insert xss payloads.

**Comment by moxi624** [comment]
I'm really sorry that I just noticed this issue recently. There may still be a problem with the background interface of uploading avatar. The format uploaded by users is not strictly verified, and only the front-end is used for processing.
I will fix this problem recently. Thank you again for your kind feedback.
This problem is the same as the other one, and I will try to fix it together：https://github.com/moxi624/mogu_blog_v2/issues/65

**Comment by moxi624** [comment]
Checking the file format on the back end should solve the problem you mentioned： https://github.com/moxi624/mogu_blog_v2/commit/2d9eb941cda8fd168f9447cd6b4262f31f074d92
