### ISSUE TITLE
nacos分支 前端无法使用ES搜索

### ISSUE THREAD

**Issue by shouyanxiang** [moxi624/mogu_blog_v2#74]
你好，在nacos分支上用docker compose部署好博客环境后，使用ES搜索功能时前端无法正常显示搜索结果：
![image](https://user-images.githubusercontent.com/104097250/196060635-febf1cdd-30a5-4251-9a2e-6c3b571b2ee7.png)

通过docker ps和nacos界面判断mogu_search container已经正常启动
![image](https://user-images.githubusercontent.com/104097250/196060519-5f42b3ef-e6bb-40f7-8dbd-5979bf8be51f.png)
![image](https://user-images.githubusercontent.com/104097250/196060564-a863cdea-3984-434b-a051-1ecc58c07bf2.png)

在后台 --> 系统配置中配置为ES并且保存：
![image](https://user-images.githubusercontent.com/104097250/196060687-0bc24061-cd9b-466c-8cb2-891db19c1694.png)

**Comment by moxi624** [comment]
需要去判断一下，mogu-search 和 elasticSearch是否启动和配置后，这个一般是 500 错误，看看日志应该就能得到答案
