### ISSUE TITLE
注册验证邮箱使用outlook怎么设置

### ISSUE THREAD

**Issue by wuchjun** [moxi624/mogu_blog_v2#79]
有人使用outlook邮箱做注册验证邮件发送邮箱的吗？怎么设置的啊？授权码是用outlook的应用密码的？

**Comment by wuchjun** [comment]
#授权码为outlook的应用密码
smtp配置如下解决：
服务器名称: smtp.office365.com
端口: 590
加密方法: STARTTLS

**Comment by moxi624** [comment]
outlook我没用过呢，应该也有类似授权码一样的东西吧

**Comment by wuchjun** [comment]
> outlook我没用过呢，应该也有类似授权码一样的东西吧

设置成功了，使用应用密码，开始配置参数搞错了，应该用下面的配置:
服务器名称: smtp.office365.com
端口: 590
加密方法: STARTTLS
